name: ceema
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: '^3.7.0'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.5
  http: ^1.2.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image: ^4.3.0
  grouped_list: ^6.0.0
  lottie: ^3.1.3
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_analytics: ^11.4.5
  flutter_rating_bar: ^4.0.1
  firebase_storage: ^12.4.4
  confetti: ^0.8.0
  youtube_player_flutter: ^9.1.1
  like_button: ^2.0.5
  url_launcher: ^6.3.1
  flutter_slidable: ^4.0.0
  shared_preferences: ^2.2.2
  photo_view: ^0.14.0
  rxdart: ^0.28.0
  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/avatars/
    - assets/images/ceema_logo.png


