// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk30WJocEXF5MKsK23aiYoF6L52M94fLI',
    appId: '1:386771880792:web:a34592add2c0e8bdfa732d',
    messagingSenderId: '386771880792',
    projectId: 'ceema-faiz',
    authDomain: 'ceema-faiz.firebaseapp.com',
    storageBucket: 'ceema-faiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0JISGclEV7O5d_cq6bIxbNX4jayfT3v0',
    appId: '1:386771880792:android:60aa950e29003c0ffa732d',
    messagingSenderId: '386771880792',
    projectId: 'ceema-faiz',
    storageBucket: 'ceema-faiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7lNo8xHtSP_CmIvhvzhHUc0I9IGalAy0',
    appId: '1:386771880792:ios:406573273af904cefa732d',
    messagingSenderId: '386771880792',
    projectId: 'ceema-faiz',
    storageBucket: 'ceema-faiz.firebasestorage.app',
    iosBundleId: 'com.example.ceema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7lNo8xHtSP_CmIvhvzhHUc0I9IGalAy0',
    appId: '1:386771880792:ios:406573273af904cefa732d',
    messagingSenderId: '386771880792',
    projectId: 'ceema-faiz',
    storageBucket: 'ceema-faiz.firebasestorage.app',
    iosBundleId: 'com.example.ceema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk30WJocEXF5MKsK23aiYoF6L52M94fLI',
    appId: '1:386771880792:web:e6693c6dc3e441eafa732d',
    messagingSenderId: '386771880792',
    projectId: 'ceema-faiz',
    authDomain: 'ceema-faiz.firebaseapp.com',
    storageBucket: 'ceema-faiz.firebasestorage.app',
  );

}